language: scala
scala:
  - 2.12.4
jdk:
  - oraclejdk8

sudo: false
cache:
  directories:
    - $HOME/.sbt/boot
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache
before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

script:
  - sbt clean coverage test
after_success:
  - sbt coverageReport coveralls
